from setuptools import setup

setup(
    name='health_to_servicenow',
    version='0.1.0',
    packages=['env.lib.python3.7.site-packages.py', 'env.lib.python3.7.site-packages.py._io',
              'env.lib.python3.7.site-packages.py._log', 'env.lib.python3.7.site-packages.py._code',
              'env.lib.python3.7.site-packages.py._path', 'env.lib.python3.7.site-packages.py._process',
              'env.lib.python3.7.site-packages.py._vendored_packages', 'env.lib.python3.7.site-packages.pip',
              'env.lib.python3.7.site-packages.pip._vendor', 'env.lib.python3.7.site-packages.pip._vendor.idna',
              'env.lib.python3.7.site-packages.pip._vendor.pep517',
              'env.lib.python3.7.site-packages.pip._vendor.pytoml',
              'env.lib.python3.7.site-packages.pip._vendor.certifi',
              'env.lib.python3.7.site-packages.pip._vendor.chardet',
              'env.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.7.site-packages.pip._vendor.distlib',
              'env.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.7.site-packages.pip._vendor.msgpack',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.rfc3986',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.7.site-packages.pip._vendor.colorama',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.7.site-packages.pip._vendor.lockfile',
              'env.lib.python3.7.site-packages.pip._vendor.progress',
              'env.lib.python3.7.site-packages.pip._vendor.requests',
              'env.lib.python3.7.site-packages.pip._vendor.packaging',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.7.site-packages.pip._vendor.webencodings',
              'env.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.7.site-packages.pip._internal', 'env.lib.python3.7.site-packages.pip._internal.cli',
              'env.lib.python3.7.site-packages.pip._internal.req', 'env.lib.python3.7.site-packages.pip._internal.vcs',
              'env.lib.python3.7.site-packages.pip._internal.utils',
              'env.lib.python3.7.site-packages.pip._internal.models',
              'env.lib.python3.7.site-packages.pip._internal.commands',
              'env.lib.python3.7.site-packages.pip._internal.operations',
              'env.lib.python3.7.site-packages.pip._internal.distributions', 'env.lib.python3.7.site-packages.attr',
              'env.lib.python3.7.site-packages.idna', 'env.lib.python3.7.site-packages.click',
              'env.lib.python3.7.site-packages.flask', 'env.lib.python3.7.site-packages.flask.json',
              'env.lib.python3.7.site-packages.jinja2', 'env.lib.python3.7.site-packages.pluggy',
              'env.lib.python3.7.site-packages._pytest', 'env.lib.python3.7.site-packages._pytest._io',
              'env.lib.python3.7.site-packages._pytest.mark', 'env.lib.python3.7.site-packages._pytest._code',
              'env.lib.python3.7.site-packages._pytest.config', 'env.lib.python3.7.site-packages._pytest.assertion',
              'env.lib.python3.7.site-packages.certifi', 'env.lib.python3.7.site-packages.chardet',
              'env.lib.python3.7.site-packages.chardet.cli', 'env.lib.python3.7.site-packages.urllib3',
              'env.lib.python3.7.site-packages.urllib3.util', 'env.lib.python3.7.site-packages.urllib3.contrib',
              'env.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'env.lib.python3.7.site-packages.urllib3.packages',
              'env.lib.python3.7.site-packages.urllib3.packages.rfc3986',
              'env.lib.python3.7.site-packages.urllib3.packages.backports',
              'env.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.7.site-packages.wcwidth', 'env.lib.python3.7.site-packages.wcwidth.tests',
              'env.lib.python3.7.site-packages.requests', 'env.lib.python3.7.site-packages.werkzeug',
              'env.lib.python3.7.site-packages.werkzeug.debug', 'env.lib.python3.7.site-packages.werkzeug.contrib',
              'env.lib.python3.7.site-packages.werkzeug.wrappers',
              'env.lib.python3.7.site-packages.werkzeug.middleware', 'env.lib.python3.7.site-packages.packaging',
              'env.lib.python3.7.site-packages.markupsafe', 'env.lib.python3.7.site-packages.setuptools',
              'env.lib.python3.7.site-packages.setuptools.extern', 'env.lib.python3.7.site-packages.setuptools._vendor',
              'env.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.7.site-packages.setuptools.command', 'env.lib.python3.7.site-packages.atomicwrites',
              'env.lib.python3.7.site-packages.itsdangerous', 'env.lib.python3.7.site-packages.pkg_resources',
              'env.lib.python3.7.site-packages.pkg_resources.extern',
              'env.lib.python3.7.site-packages.pkg_resources._vendor',
              'env.lib.python3.7.site-packages.pkg_resources._vendor.packaging',
              'env.lib.python3.7.site-packages.more_itertools', 'env.lib.python3.7.site-packages.more_itertools.tests',
              'env.lib.python3.7.site-packages.importlib_metadata',
              'env.lib.python3.7.site-packages.importlib_metadata.docs',
              'env.lib.python3.7.site-packages.importlib_metadata.tests',
              'env.lib.python3.7.site-packages.importlib_metadata.tests.data', 'tests.func', 'h_s_classes'],
    url='',
    license='CISCO SAMPLE CODE LICENSE',
    author='',
    author_email='',
    description='bridge between health insights and service now'
)
